
maven-nightly-build:
  script:
    - export MAVEN_OPTS='-Xmx128m'
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}

#    only: tags
maven-release-build:
  script:
    - export MAVEN_OPTS='-Xmx128m'
    - mvn clean package
    # need to fullfil local dependency (jpn - 20199216)
    - mvn install
  artifacts:
    paths:
    - target/*.jar
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"    
